require 'neonon.lazy.debug'
require 'neonon.lazy.autopairs'
require 'neonon.lazy.gitsigns'
require 'neonon.lazy.health'
require 'neonon.lazy.indent_line'
require 'neonon.lazy.lint'
require 'neonon.lazy.neo-tree'
